# figure out how to get .env to github and call from action yaml
# refine up statements as needed
name: weather integration test

# break this apart
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: '3.8' # add 3.9
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r dev-requirements.txt
            - name: Test with pytest
              run: python -m pytest tests/  # drop tests/
